#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Observable
version:      1.04
version_from: lib/Class/Observable.pm
installdirs:  site
requires:
    Class::ISA:                    0.32
    Scalar::Util:                  1
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
